// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xoywfkqyjqoiepxdquts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhveXdma3F5anFvaWVweGRxdXRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMzY1NzMsImV4cCI6MjA2MTkxMjU3M30._XEi9XTz1RxyIXMRhPL0Jet7qjOoPmQi5sLaDtkRVGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);